name: Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
        - DEV
        - SIT
      token:
        description: 'Personal access token'
        type: string
        required: true

env:
  BUILD_VERSION: ${{ format('{0}.{1}', vars.VERSION, github.run_number) }}

jobs:
  Setup:
    runs-on: ubuntu-latest #change
    steps:
      - name: Create environment
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: Bearer ${{ github.event.inputs.token }}' \
          https://api.github.com/repos/${{ github.repository }}/environments/${{ github.event.inputs.environment }}
      - name: Add version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh variable set VERSION --body "1.0.0"
