name: Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
        - DEV
        - SIT

env:
  BUILD_VERSION: ${{ format('{0}.{1}', vars.VERSION, github.run_number) }}

jobs:
  Setup:
    runs-on: ubuntu-latest #change
    permissions: write-all
    steps:
      - name: Create environment
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          https://api.github.com/repos/${{ github.repository }}/environments/${{ github.event.inputs.environment }}
          
