name: Setup

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: choice
        options:
        - DEV
        - SIT
      token:
        description: 'Personal access token'
        type: string
        required: true

env:
  GIT_URL: https://api.github.com/repos/${{ github.repository }}

jobs:
  Setup:
    runs-on: ubuntu-latest #change
    steps:
      - name: Create environment
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: Bearer ${{ github.event.inputs.token }}' \
          $GIT_URL/environments/${{ github.event.inputs.environment }}
      - name: Add version
        run: |
          curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H 'Authorization: Bearer ${{ github.event.inputs.token }}' \
          https://api.github.com/repos/${{ github.repository }}/actions/variables \
          -d '{"name":"VERSION","value":"1.0.0"}'
